accounting/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r"^$", views.order_create, name="order-create"),
    url(r"^orders/track/$", views.order_track, name="order-track"),
]

geo_test/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include("accounting.urls", namespace="accounting")),
]

accounting/models.py
from django.contrib.gis.db.models import PointField, GeoManager
from django.db import models


class Order(models.Model):
    # STATUS CHOICES
    PENDING = 0
    COMPLETED = 1

    STATUS_CHOICES = (
        (PENDING, "Pending"),
        (COMPLETED, "Completed"),
    )

    name = models.CharField(max_length=255, verbose_name="Name")
    status = models.IntegerField(choices=STATUS_CHOICES, default=PENDING,
                                 verbose_name="Status")
    location = PointField(geography=True, verbose_name="Location (long, lat)")
    distance = models.FloatField(verbose_name="Distance (km)",
                                 help_text="Calculated distance "
                                           "between order's location"
                                           " and New York",
                                 blank=True, null=True)

    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated At")
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name="Created At")

    objects = GeoManager()

    def __str__(self):
        return self.name

accounting/forms.py
from django import forms
from mapwidgets.widgets import GooglePointFieldWidget

from accounting.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ("name", "location",)
        widgets = {
            "location": GooglePointFieldWidget,
        }

accounting/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic import CreateView, ListView
from django_tables2 import RequestConfig

from accounting.forms import OrderForm
from accounting.models import Order
from accounting.tables import OrderTable
from accounting.tasks import calculate_location


class OrderCreateView(CreateView):
    model = Order
    form_class = OrderForm

    def form_valid(self, form):
        order = form.save()

        # Starting celery task
        calculate_location.apply_async(args=(order.pk,))

        # Updating session with the success message
        messages.add_message(self.request, messages.INFO,
                             "Order #{} ({}) have been successfully created!"
                             .format(order.pk, order.name))

        return redirect("accounting:order-track")


class OrderTrackView(ListView):
    queryset = Order.objects.all()
    context_object_name = 'orders'
    template_name = "accounting/order_track.html"

    def get_context_data(self, **kwargs):
        context = super(OrderTrackView, self).get_context_data(**kwargs)
        orders = context.get(self.context_object_name)
        orders = orders.order_by("distance")

        # Initializing Table and applying sorts
        table = OrderTable(orders)
        RequestConfig(self.request).configure(table)

        context.update(table=table)
        return context


order_create = OrderCreateView.as_view()
order_track = OrderTrackView.as_view()

accounting/templates/accounting/order_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block extrajs %}
    {{ form.media }}
{% endblock %}

{% block title %}
    Create an Order
{% endblock %}


{% block content %}
    <h1>Create an Order</h1>
    <hr>
    <form method="post" action="">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
    <hr>
    <p><a class="btn btn-primary" href="{% url "accounting:order-track" %}">Review all Orders</a></p>
{% endblock %}

accounting/templates/accounting/order_track.html
{% extends "base.html" %}

{% load django_tables2 %}

{% block title %}
    Order Tracking
{% endblock %}

{% block content %}

    {% if messages %}
        <br>
        {% for message in messages %}
            <div class="messages alert alert-info alert-dismissible">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {% if orders %}
        <br>
        {% render_table table %}
    {% else %}
        <br>
        <h3>There is no orders at this time.</h3>
    {% endif %}
    <hr>
    <p><a class="btn btn-primary" href="{% url "accounting:order-create" %}">Create new order</a></p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}{% endblock %}</title>
      <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    {% block extrajs %}
    {% endblock %}

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
  </body>
</html>